import { Investment, InvestmentAnalysis } from './types';

// Mock data generator - In production, this would fetch from real APIs
// For real implementation, you'd use APIs like:
// - Alpha Vantage API
// - Yahoo Finance API
// - IEX Cloud
// - Polygon.io

const generateMockPrice = (base: number, volatility: number = 0.02): number => {
  return base * (1 + (Math.random() - 0.5) * volatility);
};

const generateMockReturn = (base: number): number => {
  return base + (Math.random() - 0.5) * 10;
};

export const getNASDAQInvestments = (): Investment[] => {
  const nasdaqStocks: Investment[] = [
    {
      symbol: 'QQQ',
      name: 'Invesco QQQ Trust',
      type: 'ETF',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(380),
      changePercent: generateMockReturn(0.5),
      volume: 45000000,
      marketCap: 200000000000,
      peRatio: 28.5,
      dividendYield: 0.65,
      ytdReturn: 42.3,
      oneYearReturn: 38.7,
      fiveYearReturn: 18.2,
      riskLevel: 'Medium',
      recommendation: 'Strong Buy',
      recommendationScore: 92,
      description: 'Tracks the NASDAQ-100 Index, providing exposure to 100 of the largest non-financial companies listed on NASDAQ.',
      sector: 'Technology',
    },
    {
      symbol: 'TECL',
      name: 'Direxion Daily Technology Bull 3X Shares',
      type: 'ETF',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(45),
      changePercent: generateMockReturn(1.2),
      volume: 2500000,
      marketCap: 1200000000,
      peRatio: 32.1,
      dividendYield: 0.0,
      ytdReturn: 85.4,
      oneYearReturn: 72.3,
      fiveYearReturn: 25.8,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 78,
      description: '3x leveraged ETF tracking technology stocks. High risk, high reward.',
      sector: 'Technology',
    },
    {
      symbol: 'FTEC',
      name: 'Fidelity MSCI Information Technology Index ETF',
      type: 'ETF',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(125),
      changePercent: generateMockReturn(0.3),
      volume: 1200000,
      marketCap: 8500000000,
      peRatio: 29.8,
      dividendYield: 0.72,
      ytdReturn: 48.2,
      oneYearReturn: 41.5,
      fiveYearReturn: 19.3,
      riskLevel: 'Medium',
      recommendation: 'Strong Buy',
      recommendationScore: 88,
      description: 'Low-cost ETF tracking MSCI Information Technology Index.',
      sector: 'Technology',
    },
    {
      symbol: 'XLK',
      name: 'Technology Select Sector SPDR Fund',
      type: 'ETF',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(195),
      changePercent: generateMockReturn(0.4),
      volume: 15000000,
      marketCap: 55000000000,
      peRatio: 30.2,
      dividendYield: 0.68,
      ytdReturn: 45.7,
      oneYearReturn: 39.2,
      fiveYearReturn: 18.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 85,
      description: 'Tracks technology sector of S&P 500.',
      sector: 'Technology',
    },
  ];

  return nasdaqStocks.map(stock => ({
    ...stock,
    currentPrice: generateMockPrice(stock.currentPrice),
    changePercent: generateMockReturn(stock.changePercent),
  }));
};

export const getNYSEInvestments = (): Investment[] => {
  const nyseStocks: Investment[] = [
    {
      symbol: 'SPY',
      name: 'SPDR S&P 500 ETF Trust',
      type: 'ETF',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(450),
      changePercent: generateMockReturn(0.2),
      volume: 75000000,
      marketCap: 450000000000,
      peRatio: 24.8,
      dividendYield: 1.42,
      ytdReturn: 24.5,
      oneYearReturn: 22.3,
      fiveYearReturn: 14.8,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 95,
      description: 'The most popular S&P 500 ETF, providing broad market exposure with low fees.',
      sector: 'Diversified',
    },
    {
      symbol: 'VTI',
      name: 'Vanguard Total Stock Market ETF',
      type: 'ETF',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(245),
      changePercent: generateMockReturn(0.15),
      volume: 3500000,
      marketCap: 320000000000,
      peRatio: 23.5,
      dividendYield: 1.52,
      ytdReturn: 23.8,
      oneYearReturn: 21.5,
      fiveYearReturn: 14.2,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 94,
      description: 'Total stock market exposure with ultra-low expense ratio.',
      sector: 'Diversified',
    },
    {
      symbol: 'DIA',
      name: 'SPDR Dow Jones Industrial Average ETF',
      type: 'ETF',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(350),
      changePercent: generateMockReturn(0.18),
      volume: 4500000,
      marketCap: 32000000000,
      peRatio: 22.3,
      dividendYield: 1.85,
      ytdReturn: 18.7,
      oneYearReturn: 16.2,
      fiveYearReturn: 12.5,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 82,
      description: 'Tracks the Dow Jones Industrial Average, 30 blue-chip stocks.',
      sector: 'Diversified',
    },
    {
      symbol: 'IVV',
      name: 'iShares Core S&P 500 ETF',
      type: 'ETF',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(455),
      changePercent: generateMockReturn(0.2),
      volume: 5500000,
      marketCap: 380000000000,
      peRatio: 24.8,
      dividendYield: 1.40,
      ytdReturn: 24.3,
      oneYearReturn: 22.1,
      fiveYearReturn: 14.7,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 93,
      description: 'Low-cost S&P 500 ETF with strong liquidity.',
      sector: 'Diversified',
    },
  ];

  return nyseStocks.map(stock => ({
    ...stock,
    currentPrice: generateMockPrice(stock.currentPrice),
    changePercent: generateMockReturn(stock.changePercent),
  }));
};

export const getSP500Investments = (): Investment[] => {
  const sp500Stocks: Investment[] = [
    {
      symbol: 'VOO',
      name: 'Vanguard S&P 500 ETF',
      type: 'ETF',
      exchange: 'SP500',
      currentPrice: generateMockPrice(420),
      changePercent: generateMockReturn(0.2),
      volume: 4500000,
      marketCap: 380000000000,
      peRatio: 24.6,
      dividendYield: 1.45,
      ytdReturn: 24.8,
      oneYearReturn: 22.5,
      fiveYearReturn: 14.9,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 96,
      description: 'Ultra-low cost S&P 500 ETF, perfect for long-term investors.',
      sector: 'Diversified',
    },
    {
      symbol: 'SWPPX',
      name: 'Schwab S&P 500 Index Fund',
      type: 'Index Fund',
      exchange: 'SP500',
      currentPrice: generateMockPrice(85),
      changePercent: generateMockReturn(0.2),
      volume: 0,
      marketCap: 85000000000,
      peRatio: 24.7,
      dividendYield: 1.43,
      ytdReturn: 24.6,
      oneYearReturn: 22.4,
      fiveYearReturn: 14.8,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 95,
      description: 'No minimum investment S&P 500 index fund with zero commission.',
      sector: 'Diversified',
    },
    {
      symbol: 'FXAIX',
      name: 'Fidelity 500 Index Fund',
      type: 'Index Fund',
      exchange: 'SP500',
      currentPrice: generateMockPrice(165),
      changePercent: generateMockReturn(0.2),
      volume: 0,
      marketCap: 450000000000,
      peRatio: 24.8,
      dividendYield: 1.41,
      ytdReturn: 24.5,
      oneYearReturn: 22.3,
      fiveYearReturn: 14.7,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 94,
      description: 'Fidelity\'s flagship S&P 500 index fund with industry-leading low fees.',
      sector: 'Diversified',
    },
    {
      symbol: 'SPLG',
      name: 'SPDR Portfolio S&P 500 ETF',
      type: 'ETF',
      exchange: 'SP500',
      currentPrice: generateMockPrice(58),
      changePercent: generateMockReturn(0.2),
      volume: 8500000,
      marketCap: 28000000000,
      peRatio: 24.7,
      dividendYield: 1.44,
      ytdReturn: 24.4,
      oneYearReturn: 22.2,
      fiveYearReturn: 14.6,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 90,
      description: 'Low-cost S&P 500 ETF alternative with fractional share trading.',
      sector: 'Diversified',
    },
  ];

  return sp500Stocks.map(stock => ({
    ...stock,
    currentPrice: generateMockPrice(stock.currentPrice),
    changePercent: generateMockReturn(stock.changePercent),
  }));
};

// Individual stocks for broader search coverage
export const getIndividualStocks = (): Investment[] => {
  const stocks: Investment[] = [
    {
      symbol: 'F',
      name: 'Ford Motor Company',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(12.50),
      changePercent: generateMockReturn(0.3),
      volume: 45000000,
      marketCap: 50000000000,
      peRatio: 8.5,
      dividendYield: 4.2,
      ytdReturn: 15.3,
      oneYearReturn: 12.8,
      fiveYearReturn: 8.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 75,
      description: 'Ford Motor Company - American multinational automobile manufacturer. Strong dividend yield and value play.',
      sector: 'Automotive',
    },
    {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(175),
      changePercent: generateMockReturn(0.5),
      volume: 55000000,
      marketCap: 2800000000000,
      peRatio: 28.5,
      dividendYield: 0.5,
      ytdReturn: 35.2,
      oneYearReturn: 32.1,
      fiveYearReturn: 22.5,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 95,
      description: 'Apple Inc. - Technology giant known for iPhone, Mac, and services. Strong brand and cash position.',
      sector: 'Technology',
    },
    {
      symbol: 'MSFT',
      name: 'Microsoft Corporation',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(380),
      changePercent: generateMockReturn(0.4),
      volume: 25000000,
      marketCap: 2800000000000,
      peRatio: 32.1,
      dividendYield: 0.7,
      ytdReturn: 38.5,
      oneYearReturn: 35.2,
      fiveYearReturn: 24.8,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 96,
      description: 'Microsoft Corporation - Leading software and cloud services company. Strong enterprise presence.',
      sector: 'Technology',
    },
    {
      symbol: 'TSLA',
      name: 'Tesla, Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(250),
      changePercent: generateMockReturn(1.2),
      volume: 85000000,
      marketCap: 800000000000,
      peRatio: 65.2,
      dividendYield: 0.0,
      ytdReturn: 45.8,
      oneYearReturn: 42.3,
      fiveYearReturn: 35.2,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 82,
      description: 'Tesla, Inc. - Electric vehicle and clean energy company. High growth, high volatility.',
      sector: 'Automotive',
    },
    {
      symbol: 'JPM',
      name: 'JPMorgan Chase & Co.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(155),
      changePercent: generateMockReturn(0.2),
      volume: 12000000,
      marketCap: 450000000000,
      peRatio: 11.2,
      dividendYield: 2.8,
      ytdReturn: 18.5,
      oneYearReturn: 16.2,
      fiveYearReturn: 12.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 85,
      description: 'JPMorgan Chase & Co. - Largest U.S. bank by assets. Strong dividend and financial stability.',
      sector: 'Financial',
    },
    {
      symbol: 'ISRG',
      name: 'Intuitive Surgical, Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(385),
      changePercent: generateMockReturn(0.6),
      volume: 1500000,
      marketCap: 140000000000,
      peRatio: 68.5,
      dividendYield: 0.0,
      ytdReturn: 28.5,
      oneYearReturn: 25.3,
      fiveYearReturn: 18.7,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 88,
      description: 'Intuitive Surgical, Inc. - Leading manufacturer of robotic-assisted surgical systems, including the da Vinci Surgical System.',
      sector: 'Healthcare',
    },
    {
      symbol: 'NVDA',
      name: 'NVIDIA Corporation',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(485),
      changePercent: generateMockReturn(1.5),
      volume: 45000000,
      marketCap: 1200000000000,
      peRatio: 72.3,
      dividendYield: 0.03,
      ytdReturn: 185.4,
      oneYearReturn: 172.8,
      fiveYearReturn: 58.2,
      riskLevel: 'High',
      recommendation: 'Strong Buy',
      recommendationScore: 94,
      description: 'NVIDIA Corporation - Leading manufacturer of graphics processing units (GPUs) and AI computing solutions. Dominant in AI and data center markets.',
      sector: 'Technology',
    },
    {
      symbol: 'BLK',
      name: 'BlackRock, Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(780),
      changePercent: generateMockReturn(0.4),
      volume: 1200000,
      marketCap: 115000000000,
      peRatio: 22.8,
      dividendYield: 2.6,
      ytdReturn: 22.3,
      oneYearReturn: 19.5,
      fiveYearReturn: 15.2,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 87,
      description: 'BlackRock, Inc. - World\'s largest asset management company. Leader in ETFs (iShares) and investment management services.',
      sector: 'Financial',
    },
    {
      symbol: 'GOOGL',
      name: 'Alphabet Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(145),
      changePercent: generateMockReturn(0.5),
      volume: 28000000,
      marketCap: 1800000000000,
      peRatio: 26.5,
      dividendYield: 0.0,
      ytdReturn: 52.3,
      oneYearReturn: 48.7,
      fiveYearReturn: 18.5,
      riskLevel: 'Medium',
      recommendation: 'Strong Buy',
      recommendationScore: 91,
      description: 'Alphabet Inc. - Parent company of Google. Dominant in search, advertising, cloud services, and AI.',
      sector: 'Technology',
    },
    {
      symbol: 'AMZN',
      name: 'Amazon.com Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(155),
      changePercent: generateMockReturn(0.6),
      volume: 45000000,
      marketCap: 1600000000000,
      peRatio: 48.2,
      dividendYield: 0.0,
      ytdReturn: 68.5,
      oneYearReturn: 62.3,
      fiveYearReturn: 12.8,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 89,
      description: 'Amazon.com Inc. - E-commerce and cloud computing giant. Leader in AWS cloud services and online retail.',
      sector: 'Technology',
    },
    {
      symbol: 'META',
      name: 'Meta Platforms Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(485),
      changePercent: generateMockReturn(0.8),
      volume: 18000000,
      marketCap: 1200000000000,
      peRatio: 28.5,
      dividendYield: 0.4,
      ytdReturn: 142.5,
      oneYearReturn: 135.2,
      fiveYearReturn: 22.3,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 86,
      description: 'Meta Platforms Inc. - Social media and virtual reality company. Owner of Facebook, Instagram, WhatsApp, and Oculus.',
      sector: 'Technology',
    },
    {
      symbol: 'JNJ',
      name: 'Johnson & Johnson',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(165),
      changePercent: generateMockReturn(0.2),
      volume: 8000000,
      marketCap: 430000000000,
      peRatio: 25.8,
      dividendYield: 3.1,
      ytdReturn: 8.5,
      oneYearReturn: 6.2,
      fiveYearReturn: 7.8,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 83,
      description: 'Johnson & Johnson - Healthcare and pharmaceutical company. Strong dividend history and defensive stock.',
      sector: 'Healthcare',
    },
    {
      symbol: 'V',
      name: 'Visa Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(275),
      changePercent: generateMockReturn(0.3),
      volume: 7000000,
      marketCap: 570000000000,
      peRatio: 32.5,
      dividendYield: 0.7,
      ytdReturn: 18.2,
      oneYearReturn: 15.8,
      fiveYearReturn: 14.5,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 88,
      description: 'Visa Inc. - Global payments technology company. Leader in digital payments and credit card processing.',
      sector: 'Financial',
    },
    {
      symbol: 'WMT',
      name: 'Walmart Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(165),
      changePercent: generateMockReturn(0.2),
      volume: 6500000,
      marketCap: 440000000000,
      peRatio: 26.8,
      dividendYield: 1.4,
      ytdReturn: 12.5,
      oneYearReturn: 10.8,
      fiveYearReturn: 11.2,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 84,
      description: 'Walmart Inc. - World\'s largest retailer. Strong e-commerce growth and defensive characteristics.',
      sector: 'Consumer',
    },
    {
      symbol: 'MA',
      name: 'Mastercard Incorporated',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(445),
      changePercent: generateMockReturn(0.4),
      volume: 3500000,
      marketCap: 430000000000,
      peRatio: 38.2,
      dividendYield: 0.6,
      ytdReturn: 22.8,
      oneYearReturn: 20.5,
      fiveYearReturn: 19.2,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 90,
      description: 'Mastercard Incorporated - Global payment technology company. Strong growth in digital payments.',
      sector: 'Financial',
    },
    {
      symbol: 'DIS',
      name: 'The Walt Disney Company',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(95),
      changePercent: generateMockReturn(0.3),
      volume: 12000000,
      marketCap: 175000000000,
      peRatio: 72.5,
      dividendYield: 0.3,
      ytdReturn: 5.2,
      oneYearReturn: 3.8,
      fiveYearReturn: 2.5,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 72,
      description: 'The Walt Disney Company - Entertainment and media conglomerate. Theme parks, streaming (Disney+), and content.',
      sector: 'Entertainment',
    },
    {
      symbol: 'PG',
      name: 'The Procter & Gamble Company',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(165),
      changePercent: generateMockReturn(0.1),
      volume: 7000000,
      marketCap: 390000000000,
      peRatio: 26.5,
      dividendYield: 2.5,
      ytdReturn: 4.8,
      oneYearReturn: 3.2,
      fiveYearReturn: 8.5,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 81,
      description: 'The Procter & Gamble Company - Consumer goods company. Defensive stock with strong dividend yield.',
      sector: 'Consumer',
    },
    {
      symbol: 'UNH',
      name: 'UnitedHealth Group Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(525),
      changePercent: generateMockReturn(0.3),
      volume: 3200000,
      marketCap: 500000000000,
      peRatio: 28.2,
      dividendYield: 1.4,
      ytdReturn: 15.8,
      oneYearReturn: 13.5,
      fiveYearReturn: 18.2,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 86,
      description: 'UnitedHealth Group Inc. - Largest health insurer in the U.S. Strong growth in healthcare services.',
      sector: 'Healthcare',
    },
    {
      symbol: 'HD',
      name: 'The Home Depot, Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(385),
      changePercent: generateMockReturn(0.2),
      volume: 4000000,
      marketCap: 390000000000,
      peRatio: 23.5,
      dividendYield: 2.3,
      ytdReturn: 8.5,
      oneYearReturn: 6.2,
      fiveYearReturn: 16.8,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 82,
      description: 'The Home Depot, Inc. - Largest home improvement retailer. Strong dividend and consistent growth.',
      sector: 'Retail',
    },
    {
      symbol: 'BAC',
      name: 'Bank of America Corp.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(35),
      changePercent: generateMockReturn(0.3),
      volume: 45000000,
      marketCap: 280000000000,
      peRatio: 12.5,
      dividendYield: 2.8,
      ytdReturn: 18.5,
      oneYearReturn: 16.2,
      fiveYearReturn: 10.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 80,
      description: 'Bank of America Corp. - One of the largest U.S. banks. Strong dividend yield and value play.',
      sector: 'Financial',
    },
    {
      symbol: 'XOM',
      name: 'Exxon Mobil Corporation',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(105),
      changePercent: generateMockReturn(0.4),
      volume: 18000000,
      marketCap: 440000000000,
      peRatio: 13.2,
      dividendYield: 3.5,
      ytdReturn: 12.8,
      oneYearReturn: 8.5,
      fiveYearReturn: 5.2,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 75,
      description: 'Exxon Mobil Corporation - Major oil and gas company. High dividend yield, cyclical stock.',
      sector: 'Energy',
    },
    {
      symbol: 'CVX',
      name: 'Chevron Corporation',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(155),
      changePercent: generateMockReturn(0.3),
      volume: 8500000,
      marketCap: 290000000000,
      peRatio: 14.5,
      dividendYield: 4.1,
      ytdReturn: 10.2,
      oneYearReturn: 7.8,
      fiveYearReturn: 6.5,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 77,
      description: 'Chevron Corporation - Major integrated oil and gas company. Strong dividend, energy sector exposure.',
      sector: 'Energy',
    },
    // Lower-priced stocks ideal for covered call strategies
    {
      symbol: 'PLTR',
      name: 'Palantir Technologies Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(18.50),
      changePercent: generateMockReturn(1.2),
      volume: 35000000,
      marketCap: 38000000000,
      peRatio: 85.2,
      dividendYield: 0.0,
      ytdReturn: 42.5,
      oneYearReturn: 38.2,
      fiveYearReturn: 15.8,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 78,
      description: 'Palantir Technologies - Data analytics and AI company. High volatility makes it excellent for covered call premium generation.',
      sector: 'Technology',
    },
    {
      symbol: 'SOFI',
      name: 'SoFi Technologies, Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(8.25),
      changePercent: generateMockReturn(0.8),
      volume: 25000000,
      marketCap: 8500000000,
      peRatio: -45.2,
      dividendYield: 0.0,
      ytdReturn: 28.5,
      oneYearReturn: 25.3,
      fiveYearReturn: -12.5,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 72,
      description: 'SoFi Technologies - Digital financial services platform. Lower price point and volatility create strong covered call opportunities.',
      sector: 'Financial',
    },
    {
      symbol: 'RKT',
      name: 'Rocket Companies, Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(11.75),
      changePercent: generateMockReturn(0.5),
      volume: 12000000,
      marketCap: 23000000000,
      peRatio: 15.8,
      dividendYield: 4.2,
      ytdReturn: 15.2,
      oneYearReturn: 12.8,
      fiveYearReturn: -8.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 74,
      description: 'Rocket Companies - Mortgage and real estate services. High dividend yield plus covered calls create excellent income strategy.',
      sector: 'Financial',
    },
    {
      symbol: 'NOK',
      name: 'Nokia Corporation',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(3.85),
      changePercent: generateMockReturn(0.3),
      volume: 15000000,
      marketCap: 22000000000,
      peRatio: 18.5,
      dividendYield: 2.8,
      ytdReturn: 8.5,
      oneYearReturn: 6.2,
      fiveYearReturn: 3.5,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 68,
      description: 'Nokia Corporation - Telecommunications equipment. Very low price point makes covered calls accessible with high percentage returns.',
      sector: 'Technology',
    },
    {
      symbol: 'X',
      name: 'United States Steel Corporation',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(38.50),
      changePercent: generateMockReturn(0.6),
      volume: 8500000,
      marketCap: 8500000000,
      peRatio: 12.5,
      dividendYield: 0.5,
      ytdReturn: 22.5,
      oneYearReturn: 18.5,
      fiveYearReturn: 8.2,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 76,
      description: 'United States Steel - Steel production. Cyclical stock with volatility that generates strong covered call premiums.',
      sector: 'Industrial',
    },
    {
      symbol: 'CLF',
      name: 'Cleveland-Cliffs Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(19.25),
      changePercent: generateMockReturn(0.7),
      volume: 12000000,
      marketCap: 9800000000,
      peRatio: 8.5,
      dividendYield: 1.2,
      ytdReturn: 18.5,
      oneYearReturn: 15.2,
      fiveYearReturn: 12.8,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 73,
      description: 'Cleveland-Cliffs - Iron ore and steel production. Lower price with good volatility makes it ideal for covered call strategies.',
      sector: 'Industrial',
    },
    {
      symbol: 'M',
      name: 'Macy\'s, Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(15.75),
      changePercent: generateMockReturn(0.4),
      volume: 8000000,
      marketCap: 4500000000,
      peRatio: 6.2,
      dividendYield: 3.8,
      ytdReturn: -5.2,
      oneYearReturn: -8.5,
      fiveYearReturn: -12.3,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 65,
      description: 'Macy\'s - Department store retailer. High dividend yield plus covered calls can generate significant income despite stock challenges.',
      sector: 'Retail',
    },
    {
      symbol: 'T',
      name: 'AT&T Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(17.25),
      changePercent: generateMockReturn(0.2),
      volume: 35000000,
      marketCap: 123000000000,
      peRatio: 8.8,
      dividendYield: 6.8,
      ytdReturn: 5.2,
      oneYearReturn: 3.8,
      fiveYearReturn: -2.5,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 79,
      description: 'AT&T - Telecommunications and media. Exceptional dividend yield combined with covered calls creates powerful income strategy.',
      sector: 'Telecommunications',
    },
    {
      symbol: 'WBA',
      name: 'Walgreens Boots Alliance, Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(22.50),
      changePercent: generateMockReturn(0.3),
      volume: 12000000,
      marketCap: 19500000000,
      peRatio: 12.5,
      dividendYield: 4.5,
      ytdReturn: -15.2,
      oneYearReturn: -18.5,
      fiveYearReturn: -25.8,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 70,
      description: 'Walgreens Boots Alliance - Pharmacy and retail. High dividend yield makes covered calls attractive for income generation.',
      sector: 'Healthcare',
    },
    {
      symbol: 'INTC',
      name: 'Intel Corporation',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(42.50),
      changePercent: generateMockReturn(0.5),
      volume: 25000000,
      marketCap: 180000000000,
      peRatio: 28.5,
      dividendYield: 1.6,
      ytdReturn: 8.5,
      oneYearReturn: 5.2,
      fiveYearReturn: -8.5,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 71,
      description: 'Intel Corporation - Semiconductor manufacturer. Moderate price with good liquidity makes covered calls viable for income.',
      sector: 'Technology',
    },
    {
      symbol: 'SIRI',
      name: 'Sirius XM Holdings Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(4.85),
      changePercent: generateMockReturn(0.2),
      volume: 18000000,
      marketCap: 19000000000,
      peRatio: 15.2,
      dividendYield: 2.1,
      ytdReturn: 12.5,
      oneYearReturn: 8.5,
      fiveYearReturn: -5.2,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 69,
      description: 'Sirius XM Holdings - Satellite radio provider. Very low price point allows for high percentage returns from covered call premiums.',
      sector: 'Media',
    },
    {
      symbol: 'KEY',
      name: 'KeyCorp',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(13.25),
      changePercent: generateMockReturn(0.4),
      volume: 8000000,
      marketCap: 12000000000,
      peRatio: 10.5,
      dividendYield: 5.2,
      ytdReturn: 15.8,
      oneYearReturn: 12.5,
      fiveYearReturn: 8.2,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 77,
      description: 'KeyCorp - Regional bank. Excellent dividend yield combined with covered calls creates strong income opportunity.',
      sector: 'Financial',
    },
    {
      symbol: 'ARBB',
      name: 'ARB IOT Group Limited',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(2.85),
      changePercent: generateMockReturn(0.8),
      volume: 500000,
      marketCap: 15000000,
      peRatio: 12.5,
      dividendYield: 0.0,
      ytdReturn: 25.5,
      oneYearReturn: 22.3,
      fiveYearReturn: 8.5,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 72,
      description: 'ARB IOT Group - Internet of Things solutions provider. Lower price point with growth potential.',
      sector: 'Technology',
    },
    {
      symbol: 'CORZ',
      name: 'Core Scientific, Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(4.25),
      changePercent: generateMockReturn(1.5),
      volume: 8500000,
      marketCap: 1800000000,
      peRatio: -8.5,
      dividendYield: 0.0,
      ytdReturn: 85.2,
      oneYearReturn: 78.5,
      fiveYearReturn: -45.2,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 74,
      description: 'Core Scientific - Bitcoin mining and blockchain infrastructure. High volatility creates covered call opportunities.',
      sector: 'Technology',
    },
    {
      symbol: 'TM',
      name: 'Toyota Motor Corporation',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(185),
      changePercent: generateMockReturn(0.3),
      volume: 1200000,
      marketCap: 250000000000,
      peRatio: 10.5,
      dividendYield: 2.8,
      ytdReturn: 18.5,
      oneYearReturn: 15.2,
      fiveYearReturn: 12.8,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 85,
      description: 'Toyota Motor Corporation - Japanese automotive manufacturer. Strong dividend yield and global presence.',
      sector: 'Automotive',
    },
    {
      symbol: 'NKE',
      name: 'Nike, Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(105),
      changePercent: generateMockReturn(0.4),
      volume: 8500000,
      marketCap: 165000000000,
      peRatio: 28.5,
      dividendYield: 1.4,
      ytdReturn: 12.5,
      oneYearReturn: 8.5,
      fiveYearReturn: 15.2,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 83,
      description: 'Nike, Inc. - Global athletic footwear and apparel company. Strong brand and consistent growth.',
      sector: 'Consumer',
    },
    {
      symbol: 'C',
      name: 'Citigroup Inc.',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(58),
      changePercent: generateMockReturn(0.5),
      volume: 18000000,
      marketCap: 115000000000,
      peRatio: 13.2,
      dividendYield: 4.2,
      ytdReturn: 22.5,
      oneYearReturn: 18.5,
      fiveYearReturn: 8.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 81,
      description: 'Citigroup Inc. - Major global bank. Strong dividend yield and value characteristics.',
      sector: 'Financial',
    },
    {
      symbol: 'NFLX',
      name: 'Netflix, Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(485),
      changePercent: generateMockReturn(0.8),
      volume: 12000000,
      marketCap: 215000000000,
      peRatio: 42.5,
      dividendYield: 0.0,
      ytdReturn: 28.5,
      oneYearReturn: 25.2,
      fiveYearReturn: 8.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 87,
      description: 'Netflix, Inc. - Streaming entertainment service. Leader in global streaming with strong subscriber base.',
      sector: 'Entertainment',
    },
    {
      symbol: 'ORCL',
      name: 'Oracle Corporation',
      type: 'Stock',
      exchange: 'NYSE',
      currentPrice: generateMockPrice(125),
      changePercent: generateMockReturn(0.3),
      volume: 12000000,
      marketCap: 340000000000,
      peRatio: 32.5,
      dividendYield: 1.4,
      ytdReturn: 15.8,
      oneYearReturn: 12.5,
      fiveYearReturn: 18.2,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 84,
      description: 'Oracle Corporation - Enterprise software and cloud services. Strong database and cloud infrastructure business.',
      sector: 'Technology',
    },
    {
      symbol: 'AMD',
      name: 'Advanced Micro Devices, Inc.',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(145),
      changePercent: generateMockReturn(1.2),
      volume: 45000000,
      marketCap: 235000000000,
      peRatio: 285.5,
      dividendYield: 0.0,
      ytdReturn: 85.5,
      oneYearReturn: 78.2,
      fiveYearReturn: 45.8,
      riskLevel: 'High',
      recommendation: 'Strong Buy',
      recommendationScore: 92,
      description: 'Advanced Micro Devices - Semiconductor manufacturer. Strong growth in CPUs and GPUs, AI chip leader.',
      sector: 'Technology',
    },
    {
      symbol: 'COST',
      name: 'Costco Wholesale Corporation',
      type: 'Stock',
      exchange: 'NASDAQ',
      currentPrice: generateMockPrice(825),
      changePercent: generateMockReturn(0.2),
      volume: 1800000,
      marketCap: 365000000000,
      peRatio: 48.5,
      dividendYield: 0.6,
      ytdReturn: 28.5,
      oneYearReturn: 25.2,
      fiveYearReturn: 22.8,
      riskLevel: 'Low',
      recommendation: 'Strong Buy',
      recommendationScore: 93,
      description: 'Costco Wholesale - Membership-based warehouse club. Strong growth, consistent earnings, and loyal customer base.',
      sector: 'Retail',
    },
  ];

  return stocks.map(stock => ({
    ...stock,
    currentPrice: generateMockPrice(stock.currentPrice),
    changePercent: generateMockReturn(stock.changePercent),
  }));
};

// Commodities
export const getCommodities = (): Investment[] => {
  const commodities: Investment[] = [
    {
      symbol: 'GC=F',
      name: 'Gold Futures',
      type: 'Commodity',
      exchange: 'COMMODITY',
      currentPrice: generateMockPrice(2050),
      changePercent: generateMockReturn(0.3),
      volume: 150000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 8.5,
      oneYearReturn: 12.3,
      fiveYearReturn: 45.2,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 78,
      description: 'Gold Futures - Precious metal, traditional safe-haven asset. Hedge against inflation and currency devaluation.',
      sector: 'Precious Metals',
    },
    {
      symbol: 'SI=F',
      name: 'Silver Futures',
      type: 'Commodity',
      exchange: 'COMMODITY',
      currentPrice: generateMockPrice(24.50),
      changePercent: generateMockReturn(0.5),
      volume: 85000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 5.2,
      oneYearReturn: 8.5,
      fiveYearReturn: 32.8,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 72,
      description: 'Silver Futures - Industrial and precious metal. Used in electronics, solar panels, and jewelry.',
      sector: 'Precious Metals',
    },
    {
      symbol: 'CL=F',
      name: 'Crude Oil Futures',
      type: 'Commodity',
      exchange: 'COMMODITY',
      currentPrice: generateMockPrice(75.50),
      changePercent: generateMockReturn(1.2),
      volume: 250000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: -8.5,
      oneYearReturn: -5.2,
      fiveYearReturn: 15.8,
      riskLevel: 'High',
      recommendation: 'Hold',
      recommendationScore: 58,
      description: 'Crude Oil Futures (WTI) - Benchmark for oil prices. Highly volatile, influenced by geopolitics and supply/demand.',
      sector: 'Energy',
    },
    {
      symbol: 'NG=F',
      name: 'Natural Gas Futures',
      type: 'Commodity',
      exchange: 'COMMODITY',
      currentPrice: generateMockPrice(2.85),
      changePercent: generateMockReturn(2.5),
      volume: 180000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: -25.5,
      oneYearReturn: -18.2,
      fiveYearReturn: 5.2,
      riskLevel: 'High',
      recommendation: 'Hold',
      recommendationScore: 55,
      description: 'Natural Gas Futures - Clean energy transition fuel. Seasonal volatility based on weather and storage levels.',
      sector: 'Energy',
    },
    {
      symbol: 'HG=F',
      name: 'Copper Futures',
      type: 'Commodity',
      exchange: 'COMMODITY',
      currentPrice: generateMockPrice(3.85),
      changePercent: generateMockReturn(0.8),
      volume: 95000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 2.5,
      oneYearReturn: 5.8,
      fiveYearReturn: 28.5,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 68,
      description: 'Copper Futures - Industrial metal essential for construction, electronics, and renewable energy infrastructure.',
      sector: 'Industrial Metals',
    },
    {
      symbol: 'ZC=F',
      name: 'Corn Futures',
      type: 'Commodity',
      exchange: 'COMMODITY',
      currentPrice: generateMockPrice(4.85),
      changePercent: generateMockReturn(0.5),
      volume: 120000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: -12.5,
      oneYearReturn: -8.2,
      fiveYearReturn: 15.3,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 62,
      description: 'Corn Futures - Agricultural commodity. Influenced by weather, global demand, and biofuel production.',
      sector: 'Agriculture',
    },
  ];

  return commodities.map(commodity => ({
    ...commodity,
    currentPrice: generateMockPrice(commodity.currentPrice),
    changePercent: generateMockReturn(commodity.changePercent),
  }));
};

// Cryptocurrencies
export const getCryptocurrencies = (): Investment[] => {
  const cryptocurrencies: Investment[] = [
    {
      symbol: 'BTC-USD',
      name: 'Bitcoin',
      type: 'Cryptocurrency',
      exchange: 'CRYPTO',
      currentPrice: generateMockPrice(43500),
      changePercent: generateMockReturn(2.5),
      volume: 15000000000,
      marketCap: 850000000000,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 125.5,
      oneYearReturn: 142.8,
      fiveYearReturn: 285.2,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 82,
      description: 'Bitcoin (BTC) - First and largest cryptocurrency by market cap. Digital gold, store of value, decentralized digital currency.',
      sector: 'Cryptocurrency',
    },
    {
      symbol: 'ETH-USD',
      name: 'Ethereum',
      type: 'Cryptocurrency',
      exchange: 'CRYPTO',
      currentPrice: generateMockPrice(2650),
      changePercent: generateMockReturn(3.2),
      volume: 8500000000,
      marketCap: 320000000000,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 88.5,
      oneYearReturn: 95.2,
      fiveYearReturn: 185.5,
      riskLevel: 'High',
      recommendation: 'Buy',
      recommendationScore: 85,
      description: 'Ethereum (ETH) - Second-largest cryptocurrency. Smart contract platform, DeFi, NFTs, and Web3 infrastructure.',
      sector: 'Cryptocurrency',
    },
  ];

  return cryptocurrencies.map(crypto => ({
    ...crypto,
    currentPrice: generateMockPrice(crypto.currentPrice),
    changePercent: generateMockReturn(crypto.changePercent),
  }));
};

// Indices
export const getIndices = (): Investment[] => {
  const indices: Investment[] = [
    {
      symbol: '^FTSE',
      name: 'FTSE 100 Index',
      type: 'Index',
      exchange: 'LSE',
      currentPrice: generateMockPrice(7650),
      changePercent: generateMockReturn(0.4),
      volume: 0,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: 3.8,
      ytdReturn: 5.2,
      oneYearReturn: 8.5,
      fiveYearReturn: 12.3,
      riskLevel: 'Low',
      recommendation: 'Buy',
      recommendationScore: 80,
      description: 'FTSE 100 Index - Top 100 companies listed on the London Stock Exchange. UK blue-chip index, strong dividend yield.',
      sector: 'Index',
    },
  ];

  return indices.map(index => ({
    ...index,
    currentPrice: generateMockPrice(index.currentPrice),
    changePercent: generateMockReturn(index.changePercent),
  }));
};

// Foreign Exchange (FX) Pairs
export const getFXPairs = (): Investment[] => {
  const fxPairs: Investment[] = [
    {
      symbol: 'EURUSD',
      name: 'Euro / U.S. Dollar',
      type: 'FX',
      exchange: 'FX',
      currentPrice: generateMockPrice(1.0850),
      changePercent: generateMockReturn(0.1),
      volume: 500000000000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 2.5,
      oneYearReturn: 3.2,
      fiveYearReturn: -5.8,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 65,
      description: 'EUR/USD - Most traded currency pair. Euro vs U.S. Dollar. Influenced by ECB and Fed monetary policy.',
      sector: 'Forex',
    },
    {
      symbol: 'GBPUSD',
      name: 'British Pound / U.S. Dollar',
      type: 'FX',
      exchange: 'FX',
      currentPrice: generateMockPrice(1.2650),
      changePercent: generateMockReturn(0.2),
      volume: 350000000000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 3.8,
      oneYearReturn: 5.2,
      fiveYearReturn: -8.5,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 68,
      description: 'GBP/USD - British Pound vs U.S. Dollar. Cable pair, influenced by UK economic data and Bank of England policy.',
      sector: 'Forex',
    },
    {
      symbol: 'USDJPY',
      name: 'U.S. Dollar / Japanese Yen',
      type: 'FX',
      exchange: 'FX',
      currentPrice: generateMockPrice(149.50),
      changePercent: generateMockReturn(0.3),
      volume: 450000000000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 8.5,
      oneYearReturn: 12.3,
      fiveYearReturn: 25.2,
      riskLevel: 'Medium',
      recommendation: 'Buy',
      recommendationScore: 72,
      description: 'USD/JPY - U.S. Dollar vs Japanese Yen. Influenced by Bank of Japan policy and U.S. interest rates.',
      sector: 'Forex',
    },
    {
      symbol: 'USDCHF',
      name: 'U.S. Dollar / Swiss Franc',
      type: 'FX',
      exchange: 'FX',
      currentPrice: generateMockPrice(0.8750),
      changePercent: generateMockReturn(0.1),
      volume: 120000000000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 1.5,
      oneYearReturn: 2.8,
      fiveYearReturn: -3.2,
      riskLevel: 'Low',
      recommendation: 'Hold',
      recommendationScore: 60,
      description: 'USD/CHF - U.S. Dollar vs Swiss Franc. Safe-haven pair, influenced by SNB interventions and risk sentiment.',
      sector: 'Forex',
    },
    {
      symbol: 'AUDUSD',
      name: 'Australian Dollar / U.S. Dollar',
      type: 'FX',
      exchange: 'FX',
      currentPrice: generateMockPrice(0.6650),
      changePercent: generateMockReturn(0.4),
      volume: 180000000000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: -2.5,
      oneYearReturn: -1.8,
      fiveYearReturn: -12.5,
      riskLevel: 'Medium',
      recommendation: 'Hold',
      recommendationScore: 58,
      description: 'AUD/USD - Australian Dollar vs U.S. Dollar. Commodity currency, influenced by China demand and RBA policy.',
      sector: 'Forex',
    },
    {
      symbol: 'USDCAD',
      name: 'U.S. Dollar / Canadian Dollar',
      type: 'FX',
      exchange: 'FX',
      currentPrice: generateMockPrice(1.3450),
      changePercent: generateMockReturn(0.2),
      volume: 150000000000,
      marketCap: undefined,
      peRatio: undefined,
      dividendYield: undefined,
      ytdReturn: 1.2,
      oneYearReturn: 2.5,
      fiveYearReturn: 5.8,
      riskLevel: 'Low',
      recommendation: 'Hold',
      recommendationScore: 62,
      description: 'USD/CAD - U.S. Dollar vs Canadian Dollar. Loonie, influenced by oil prices and Bank of Canada policy.',
      sector: 'Forex',
    },
  ];

  return fxPairs.map(fx => ({
    ...fx,
    currentPrice: generateMockPrice(fx.currentPrice),
    changePercent: generateMockReturn(fx.changePercent),
  }));
};

export const analyzeInvestments = (): InvestmentAnalysis => {
  const nasdaq = getNASDAQInvestments();
  const nyse = getNYSEInvestments();
  const sp500 = getSP500Investments();
  const stocks = getIndividualStocks();
  const commodities = getCommodities();
  const cryptocurrencies = getCryptocurrencies();
  const indices = getIndices();
  const fxPairs = getFXPairs();
  
  const allInvestments = [...nasdaq, ...nyse, ...sp500, ...stocks, ...commodities, ...cryptocurrencies, ...indices, ...fxPairs];
  
  // Calculate average returns
  const nasdaqAvg = nasdaq.reduce((sum, inv) => sum + (inv.ytdReturn || 0), 0) / nasdaq.length;
  const nyseAvg = nyse.reduce((sum, inv) => sum + (inv.ytdReturn || 0), 0) / nyse.length;
  const sp500Avg = sp500.reduce((sum, inv) => sum + (inv.ytdReturn || 0), 0) / sp500.length;
  
  // Sort by recommendation score
  const topRecommendations = [...allInvestments]
    .sort((a, b) => b.recommendationScore - a.recommendationScore)
    .slice(0, 10);
  
  return {
    investments: allInvestments,
    totalCount: allInvestments.length,
    topRecommendations,
    marketSummary: {
      nasdaqAvgReturn: nasdaqAvg,
      nyseAvgReturn: nyseAvg,
      sp500AvgReturn: sp500Avg,
    },
  };
};

